trigger:
- master

pool:
  name: linuxvm

steps:
# Prepare SonarCloud
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonaraccess'        # Service connection name in DevOps
    organization: 'amitow23'         # Your SonarCloud org
    scannerMode: 'Other'
    configMode: 'manual'
    projectKey: 'amitow23_amitow'    # Replace with your actual project key
    projectName: 'MyJavaApp'         # Optional

# Build & run Sonar scan with Maven
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    goals: 'clean verify sonar:sonar'
    options: >
      -Dsonar.userHome=$(Pipeline.Workspace)/.sonar

# Publish results to SonarCloud
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
